wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1645582334
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 16
      4: 3.8.12
      5: 0.12.10
      8:
      - 5
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 195
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 6
fc_layer_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.08646997493551557
optimizer:
  desc: null
  value: sgd
seed:
  desc: null
  value: 42
weight_decay:
  desc: null
  value: 0.0005
